//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOLDSOFT.QDJJ.UI.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebSuoSoap")]
    public interface WebSuoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSuoInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getSuoInfo(string suoCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SynchronousData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet SynchronousData(System.Data.DataSet p_DataSet, string p_CurrNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInformationPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable GetInformationPrice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInformationPrice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable UpdateInformationPrice(System.DateTime p_DateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SharingWwitch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool SharingWwitch(string p_CurrNo, bool p_Switch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSharingWwitch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        bool GetSharingWwitch(string p_CurrNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebSuoSoapChannel : GOLDSOFT.QDJJ.UI.ServiceReference1.WebSuoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebSuoSoapClient : System.ServiceModel.ClientBase<GOLDSOFT.QDJJ.UI.ServiceReference1.WebSuoSoap>, GOLDSOFT.QDJJ.UI.ServiceReference1.WebSuoSoap {
        
        public WebSuoSoapClient() {
        }
        
        public WebSuoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebSuoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSuoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebSuoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable getSuoInfo(string suoCode) {
            return base.Channel.getSuoInfo(suoCode);
        }
        
        public System.Data.DataSet SynchronousData(System.Data.DataSet p_DataSet, string p_CurrNo) {
            return base.Channel.SynchronousData(p_DataSet, p_CurrNo);
        }
        
        public System.Data.DataTable GetInformationPrice() {
            return base.Channel.GetInformationPrice();
        }
        
        public System.Data.DataTable UpdateInformationPrice(System.DateTime p_DateTime) {
            return base.Channel.UpdateInformationPrice(p_DateTime);
        }
        
        public bool SharingWwitch(string p_CurrNo, bool p_Switch) {
            return base.Channel.SharingWwitch(p_CurrNo, p_Switch);
        }
        
        public bool GetSharingWwitch(string p_CurrNo) {
            return base.Channel.GetSharingWwitch(p_CurrNo);
        }
    }
}
