//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3625
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections;
using System.Collections.Generic;

// 
// 此源代码由 xsd 自动生成, Version=2.0.50727.42。
// 

namespace GOLDSOFT.QDJJ.COMMONS.ZBS
{
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 专业工程暂估价明细表 {
    
    private 专业工程暂估明细[] 专业工程暂估明细Field;
    
    /// <remarks/>
   
    [XmlElementAttribute("专业工程暂估明细", IsNullable = false)]  
    public 专业工程暂估明细[] 专业工程暂估明细 {
        get {
            return this.专业工程暂估明细Field;
        }
        set {
            this.专业工程暂估明细Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 专业工程暂估明细 {

    private string 序号Field;
    
    private string 项目名称Field;
    
    private string 计量单位Field;
    
    private string 暂估单价Field;
    
    private string 备注Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号 {
        get {
            return this.序号Field;
        }
        set {
            this.序号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 项目名称 {
        get {
            return this.项目名称Field;
        }
        set {
            this.项目名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 计量单位 {
        get {
            return this.计量单位Field;
        }
        set {
            this.计量单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 暂估单价
    {
        get {
            return this.暂估单价Field;
        }
        set {
            this.暂估单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 备注 {
        get {
            return this.备注Field;
        }
        set {
            this.备注Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 其他项目清单 {
    
    private string 序号Field;
    
    private string 项目名称Field;
    
    private string 计量单位Field;
    
    private string 工程数量Field;
    
    private string 综合单价Field;
    
    private string 合价Field;
    
    private string 费用类型Field;

    private string 名称Field;
    private string 单位Field;
    private string 工程量Field;
    private string 计算基础Field;
    private string 费率Field;
    private string 单价Field;

    private string 类别Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号 {
        get {
            return this.序号Field;
        }
        set {
            this.序号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 项目名称 {
        get {
            return this.项目名称Field;
        }
        set {
            this.项目名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 计量单位 {
        get {
            return this.计量单位Field;
        }
        set {
            this.计量单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 工程数量 {
        get {
            return this.工程数量Field;
        }
        set {
            this.工程数量Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 综合单价 {
        get {
            return this.综合单价Field;
        }
        set {
            this.综合单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 合价 {
        get {
            return this.合价Field;
        }
        set {
            this.合价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 费用类型 {
        get {
            return this.费用类型Field;
        }
        set {
            this.费用类型Field = value;
        }
    }



   
   
    /// <summary>
    /// 零星项目会用到
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 名称
    {
        get
        {
            return this.名称Field;
        }
        set
        {
            this.名称Field = value;
        }
    }
    /// <summary>
    /// 零星项目会用到
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 单位
    {
        get
        {
            return this.单位Field;
        }
        set
        {
            this.单位Field = value;
        }
    }
    /// <summary>
    /// 零星项目会用到
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 工程量
    {
        get
        {
            return this.工程量Field;
        }
        set
        {
            this.工程量Field = value;
        }
    }
    /// <summary>
    /// 零星项目会用到
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 计算基础
    {
        get
        {
            return this.计算基础Field;
        }
        set
        {
            this.计算基础Field = value;
        }
    }
    /// <summary>
    /// 零星项目会用到
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 费率
    {
        get
        {
            return this.费率Field;
        }
        set
        {
            this.费率Field = value;
        }
    }
    /// <summary>
    /// 零星项目会用到
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 单价
    {
        get
        {
            return this.单价Field;
        }
        set
        {
            this.单价Field = value;
        }
    }
    /// <summary>
    /// 零星项目会用到
    /// </summary>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 类别
    {
        get
        {
            return this.类别Field;
        }
        set
        {
            this.类别Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 其他项目表 {
    private 其他项目清单[] m_其他项目清单;
    private 暂列金额明细表 m_暂列金额明细表;
    private 专业工程暂估价明细表 m_专业工程暂估价明细表;
    private 计日工表 m_计日工表;
    private 总承包服务费项目表 m_总承包服务费项目表;

    [XmlElementAttribute("其他项目清单", IsNullable = false)]  
    public 其他项目清单[] 其他项目清单
    {
        get { return m_其他项目清单; }
        set { m_其他项目清单 = value; }
    }
    public 暂列金额明细表 暂列金额明细表
    {
        get { return m_暂列金额明细表; }
        set { m_暂列金额明细表 = value; }
    }
    public 专业工程暂估价明细表 专业工程暂估价明细表
    {
        get { return m_专业工程暂估价明细表; }
        set { m_专业工程暂估价明细表 = value; }
    }
    public 计日工表 计日工表
    {
        get { return m_计日工表; }
        set { m_计日工表 = value; }
    }

    public 总承包服务费项目表 总承包服务费项目表
    {
        get { return m_总承包服务费项目表; }
        set { m_总承包服务费项目表 = value; }
    }

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 分部分项表 {
    
    private 分部分项清单[] 分部分项清单Field;
    
    /// <remarks/>
    /// 

    [XmlElementAttribute("分部分项清单", IsNullable = false)]
     public 分部分项清单[] 分部分项清单 {
        get {
            return this.分部分项清单Field;
        }
        set {
            this.分部分项清单Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 分部分项清单 {

    private string 序号Field;
    private string 清单编码Field;
    
    private string 名称Field;
    
    private string 项目特征及工作内容Field;
    
    private string 单位Field;

    private string 数量Field;
    
    private string 综合单价Field;
    
    private string 综合合价Field;
    
    private string 人工费单价Field;

    private string 材料费单价Field;

    private string 机械费单价Field;

    private string 主材费单价Field;

    private string 设备费单价Field;

    private string 管理费单价Field;

    private string 利润单价Field;

    private string 风险单价Field;

    private string 规费单价Field;

    private string 税金单价Field;
    
    private string 管理费计费基础Field;
    
    private string 管理费费率Field;
    
    private string 利润计费基础Field;
    
    private string 利润费率Field;
    
    private string 风险计费基础Field;
    
    private string 风险费率Field;
    
    private string 规费计费基础Field;
    
    private string 规费费率Field;
    
    private string 税金计费基础Field;
    
    private string 税金费率Field;
    
    private bool 主要清单Field;
    
    private string 专业类别Field;

    private List<定额子目> m_定额子目;


    [XmlElementAttribute("定额子目", IsNullable = false)] 
    public List<定额子目> 定额子目
    {
      get { return m_定额子目; }
      set { m_定额子目 = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号
    {
        get
        {
            return this.序号Field;
        }
        set
        {
            this.序号Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 清单编码 {
        get {
            return this.清单编码Field;
        }
        set {
            this.清单编码Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 名称 {
        get {
            return this.名称Field;
        }
        set {
            this.名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 项目特征及工作内容 {
        get {
            return this.项目特征及工作内容Field;
        }
        set {
            this.项目特征及工作内容Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 单位 {
        get {
            return this.单位Field;
        }
        set {
            this.单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 数量 {
        get {
            return this.数量Field;
        }
        set {
            this.数量Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 综合单价 {
        get {
            return this.综合单价Field;
        }
        set {
            this.综合单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 综合合价 {
        get {
            return this.综合合价Field;
        }
        set {
            this.综合合价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 人工费单价
    {
        get {
            return this.人工费单价Field;
        }
        set {
            this.人工费单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 材料费单价
    {
        get {
            return this.材料费单价Field;
        }
        set {
            this.材料费单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 机械费单价
    {
        get {
            return this.机械费单价Field;
        }
        set {
            this.机械费单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 主材费单价
    {
        get {
            return this.主材费单价Field;
        }
        set {
            this.主材费单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 设备费单价
    {
        get {
            return this.设备费单价Field;
        }
        set {
            this.设备费单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 管理费单价
    {
        get {
            return this.管理费单价Field;
        }
        set {
            this.管理费单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 利润单价
    {
        get {
            return this.利润单价Field;
        }
        set {
            this.利润单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 风险单价
    {
        get {
            return this.风险单价Field;
        }
        set {
            this.风险单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 规费单价 {
        get {
            return this.规费单价Field;
        }
        set {
            this.规费单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 税金单价
    {
        get {
            return this.税金单价Field;
        }
        set {
            this.税金单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 管理费计费基础 {
        get {
            return this.管理费计费基础Field;
        }
        set {
            this.管理费计费基础Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 管理费费率 {
        get {
            return this.管理费费率Field;
        }
        set {
            this.管理费费率Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 利润计费基础 {
        get {
            return this.利润计费基础Field;
        }
        set {
            this.利润计费基础Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 利润费率 {
        get {
            return this.利润费率Field;
        }
        set {
            this.利润费率Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 风险计费基础 {
        get {
            return this.风险计费基础Field;
        }
        set {
            this.风险计费基础Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 风险费率 {
        get {
            return this.风险费率Field;
        }
        set {
            this.风险费率Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 规费计费基础 {
        get {
            return this.规费计费基础Field;
        }
        set {
            this.规费计费基础Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 规费费率 {
        get {
            return this.规费费率Field;
        }
        set {
            this.规费费率Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 税金计费基础 {
        get {
            return this.税金计费基础Field;
        }
        set {
            this.税金计费基础Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 税金费率 {
        get {
            return this.税金费率Field;
        }
        set {
            this.税金费率Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool 主要清单 {
        get {
            return this.主要清单Field;
        }
        set {
            this.主要清单Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 专业类别 {
        get {
            return this.专业类别Field;
        }
        set {
            this.专业类别Field = value;
        }
    }
}










/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 单位工程 {


    private 单位工程造价汇总表 单位工程造价汇总表Field;
    private 分部分项表 分部分项表Field;
    private 措施项目表 措施项目表Field;
    private 其他项目表 其他项目表Field;
    private 零星项目表 零星项目表Field;
    private 需评审的材料表 需评审的材料表Field;

    private 材料设备暂估价 材料设备暂估价Field;
    private 甲供材料或设备表 甲供材料或设备表Field;
    private 人材机库 人材机库Field;
    private 三大材 三大材Field;
    private 规费税金清单表 规费税金清单表Field;


    private string 单位工程名称Field;
    private string 清单专业Field;
    private string 定额专业Field;

    public 单位工程造价汇总表 单位工程造价汇总表
    {
        get { return 单位工程造价汇总表Field; }
        set { 单位工程造价汇总表Field = value; }
    }

   
    public 分部分项表 分部分项表
    {
        get { return 分部分项表Field; }
        set { 分部分项表Field = value; }
    }
    public 措施项目表 措施项目表
    {
        get { return 措施项目表Field; }
        set { 措施项目表Field = value; }
    }
    public 其他项目表 其他项目表
    {
        get { return 其他项目表Field; }
        set { 其他项目表Field = value; }
    }

    [XmlElementAttribute("零星项目表", IsNullable = false)]
    public 零星项目表 零星项目表
    {
        get { return 零星项目表Field; }
        set { 零星项目表Field = value; }
    }
    public 需评审的材料表 需评审的材料表
    {
        get { return 需评审的材料表Field; }
        set { 需评审的材料表Field = value; }
    }
    public 材料设备暂估价 材料设备暂估价
    {
        get { return 材料设备暂估价Field; }
        set { 材料设备暂估价Field = value; }
    }
    public 甲供材料或设备表 甲供材料或设备表
    {
        get { return 甲供材料或设备表Field; }
        set { 甲供材料或设备表Field = value; }
    }
    public 人材机库 人材机库
    {
        get { return 人材机库Field; }
        set { 人材机库Field = value; }
    }
    public 三大材 三大材
    {
        get { return 三大材Field; }
        set { 三大材Field = value; }
    }
    public 规费税金清单表 规费税金清单表
    {
        get { return 规费税金清单表Field; }
        set { 规费税金清单表Field = value; }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 单位工程名称 {
        get {
            return this.单位工程名称Field;
        }
        set {
            this.单位工程名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 清单专业 {
        get {
            return this.清单专业Field;
        }
        set {
            this.清单专业Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 定额专业 {
        get {
            return this.定额专业Field;
        }
        set {
            this.定额专业Field = value;
        }
    }
    private string m_电脑串号;
    private string m_时间;
    private string m_锁号;
    private string m_工程代号;

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 工程代号
    {
        get { return m_工程代号; }
        set { m_工程代号 = value; }
    }



    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 电脑串号
    {
        get { return m_电脑串号; }
        set { m_电脑串号 = value; }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 时间
    {
        get { return m_时间; }
        set { m_时间 = value; }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 锁号
    {
        get { return m_锁号; }
        set { m_锁号 = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 单位工程费用项 {
    
    private string 序号Field;
    
    private string 费用名称Field;
    
    private string 行费用代号Field;
    
    private string 取费基数Field;

    private string 费率Field;

    private string 金额Field;
    
    private string 费用类别Field;
    
    private bool 合计行Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号 {
        get {
            return this.序号Field;
        }
        set {
            this.序号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 费用名称 {
        get {
            return this.费用名称Field;
        }
        set {
            this.费用名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 行费用代号 {
        get {
            return this.行费用代号Field;
        }
        set {
            this.行费用代号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 取费基数 {
        get {
            return this.取费基数Field;
        }
        set {
            this.取费基数Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 费率
    {
        get {
            return this.费率Field;
        }
        set {
            this.费率Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 金额
    {
        get {
            return this.金额Field;
        }
        set {
            this.金额Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 费用类别 {
        get {
            return this.费用类别Field;
        }
        set {
            this.费用类别Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool 合计行 {
        get {
            return this.合计行Field;
        }
        set {
            this.合计行Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 三大材
{

    private List<人材机> M_人才机;

    [XmlElementAttribute("人材机", IsNullable = false)]
    public List<人材机> 人才机
    {
        get { return M_人才机; }
        set { M_人才机 = value; }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 单位工程造价汇总表 {
    
    private 单位工程费用项[] 单位工程费用项Field;
    
    /// <remarks/>
    [XmlElementAttribute("单位工程费用项", IsNullable = false)]
    public 单位工程费用项[] 单位工程费用项 {
        get {
            return this.单位工程费用项Field;
        }
        set {
            this.单位工程费用项Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=false)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class 建设项目 {
    
    private 招标信息表 招标信息表Field;
    private 投标信息表 投标信息表Field;
    private 单项工程[] 单项工程Field;
    
    private string 标准名称Field;
    
    private string 标准版本号Field;
    
    private string 报建号Field;
    
    private string 项目名称Field;
    
    /// <remarks/>
    public 招标信息表 招标信息表 {
        get {
            return this.招标信息表Field;
        }
        set {
            this.招标信息表Field = value;
        }
    }
      
    /// <remarks/>
    public 投标信息表 投标信息表
    {
        get {
            return this.投标信息表Field;
        }
        set {
            this.投标信息表Field = value;
        }
    }
    /// <remarks/>
    [XmlElementAttribute("单项工程", IsNullable = false)]
    public 单项工程[] 单项工程 {
        get {
            return this.单项工程Field;
        }
        set {
            this.单项工程Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 标准名称 {
        get {
            return this.标准名称Field;
        }
        set {
            this.标准名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 标准版本号 {
        get {
            return this.标准版本号Field;
        }
        set {
            this.标准版本号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 报建号 {
        get {
            return this.报建号Field;
        }
        set {
            this.报建号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 项目名称 {
        get {
            return this.项目名称Field;
        }
        set {
            this.项目名称Field = value;
        }

        
    }
    //private string m_电脑串号;
    //private string m_时间;
    //private string m_锁号;
    //private string m_工程代号;

    //[System.Xml.Serialization.XmlAttributeAttribute()]
    //public string 工程代号
    //{
    //    get { return m_工程代号; }
    //    set { m_工程代号 = value; }
    //}

    //[System.Xml.Serialization.XmlAttributeAttribute()]
    //public string 电脑串号
    //{
    //    get { return m_电脑串号; }
    //    set { m_电脑串号 = value; }
    //}
    //[System.Xml.Serialization.XmlAttributeAttribute()]
    //public string 时间
    //{
    //    get { return m_时间; }
    //    set { m_时间 = value; }
    //}
    //[System.Xml.Serialization.XmlAttributeAttribute()]
    //public string 锁号
    //{
    //    get { return m_锁号; }
    //    set { m_锁号 = value; }
    //}

}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 招标信息表 {
    
    private string 工程类型Field;
    
    private string 建设单位Field;
    
    private string 招标代理Field;
    
    private string 工程地点Field;

    private string 计价依据Field;
    
    private string 招标范围Field;
    
    private string 总招标面积Field;
    
    private string 招标工期Field;
    
    private string 编制人员1Field;
    
    private string 注册号1Field;
    
    private string 编制人员2Field;
    
    private string 注册号2Field;
    
    private string 编制人员3Field;
    
    private string 注册号3Field;
    
    private string 编制单位Field;
    
    private string 设计单位Field;
    
    private string 编制时间Field;
    
    private string 招标要求担保类型Field;
    
    private string 纳税地区类别Field;
    
    private string 备注Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 工程类型 {
        get {
            return this.工程类型Field;
        }
        set {
            this.工程类型Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 建设单位 {
        get {
            return this.建设单位Field;
        }
        set {
            this.建设单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 招标代理 {
        get {
            return this.招标代理Field;
        }
        set {
            this.招标代理Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 工程地点 {
        get {
            return this.工程地点Field;
        }
        set {
            this.工程地点Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 计价依据 {
        get {
            return this.计价依据Field;
        }
        set {
            this.计价依据Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 招标范围 {
        get {
            return this.招标范围Field;
        }
        set {
            this.招标范围Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 总招标面积 {
        get {
            return this.总招标面积Field;
        }
        set {
            this.总招标面积Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 招标工期 {
        get {
            return this.招标工期Field;
        }
        set {
            this.招标工期Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编制人员1 {
        get {
            return this.编制人员1Field;
        }
        set {
            this.编制人员1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 注册号1 {
        get {
            return this.注册号1Field;
        }
        set {
            this.注册号1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编制人员2 {
        get {
            return this.编制人员2Field;
        }
        set {
            this.编制人员2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 注册号2 {
        get {
            return this.注册号2Field;
        }
        set {
            this.注册号2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编制人员3 {
        get {
            return this.编制人员3Field;
        }
        set {
            this.编制人员3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 注册号3 {
        get {
            return this.注册号3Field;
        }
        set {
            this.注册号3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编制单位 {
        get {
            return this.编制单位Field;
        }
        set {
            this.编制单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 设计单位 {
        get {
            return this.设计单位Field;
        }
        set {
            this.设计单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编制时间 {
        get {
            return this.编制时间Field;
        }
        set {
            this.编制时间Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 招标要求担保类型 {
        get {
            return this.招标要求担保类型Field;
        }
        set {
            this.招标要求担保类型Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 纳税地区类别 {
        get {
            return this.纳税地区类别Field;
        }
        set {
            this.纳税地区类别Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 备注 {
        get {
            return this.备注Field;
        }
        set {
            this.备注Field = value;
        }
    }


    private string m_电脑串号;
    private string m_时间;
    private string m_锁号;
    private string m_工程代号;

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 工程代号
    {
        get { return m_工程代号; }
        set { m_工程代号 = value; }
    }



    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 电脑串号
    {
        get { return m_电脑串号; }
        set { m_电脑串号 = value; }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 时间
    {
        get { return m_时间; }
        set { m_时间 = value; }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 锁号
    {
        get { return m_锁号; }
        set { m_锁号 = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 单项工程 {
    
    private 单位工程[] 单位工程Field;
    
    private string 单项工程名称Field;
    
    private string 建筑面积Field;
    private List<工程特征> m_工程特征;



    /// <remarks/>
    /// 
    [XmlElementAttribute("工程特征", IsNullable = false)]
    public List<工程特征> 工程特征
    {
        get
        {
            return this.m_工程特征;
        }
        set
        {
            this.m_工程特征 = value;
        }
    }

    /// <remarks/>
    /// 
    [XmlElementAttribute("单位工程", IsNullable = false)]
    public 单位工程[] 单位工程 {
        get {
            return this.单位工程Field;
        }
        set {
            this.单位工程Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 单项工程名称 {
        get {
            return this.单项工程名称Field;
        }
        set {
            this.单项工程名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 建筑面积 {
        get {
            return this.建筑面积Field;
        }
        set {
            this.建筑面积Field = value;
        }

    }
    private string m_电脑串号;
    private string m_时间;
    private string m_锁号;
    private string m_工程代号;

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 工程代号
    {
        get { return m_工程代号; }
        set { m_工程代号 = value; }
    }



    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 电脑串号
    {
        get { return m_电脑串号; }
        set { m_电脑串号 = value; }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 时间
    {
        get { return m_时间; }
        set { m_时间 = value; }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 锁号
    {
        get { return m_锁号; }
        set { m_锁号 = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 总承包服务费项 {
    
    private string 序号Field;
    
    private string 项目名称Field;
    
    private string 计量单位Field;
    
    private string 工程数量Field;
    
    private string 综合单价Field;
    
    private string 合价Field;
    
    private string 类别Field;
    
    private string 备注Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号 {
        get {
            return this.序号Field;
        }
        set {
            this.序号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 项目名称 {
        get {
            return this.项目名称Field;
        }
        set {
            this.项目名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 计量单位 {
        get {
            return this.计量单位Field;
        }
        set {
            this.计量单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 工程数量 {
        get {
            return this.工程数量Field;
        }
        set {
            this.工程数量Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 综合单价 {
        get {
            return this.综合单价Field;
        }
        set {
            this.综合单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 合价 {
        get {
            return this.合价Field;
        }
        set {
            this.合价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 类别 {
        get {
            return this.类别Field;
        }
        set {
            this.类别Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 备注 {
        get {
            return this.备注Field;
        }
        set {
            this.备注Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 总承包服务费项目表 {
    
    private 总承包服务费项[] 总承包服务费项Field;
    
    /// <remarks/>
    [XmlElementAttribute("总承包服务费项", IsNullable = false)] 
    public 总承包服务费项[] 总承包服务费项 {
        get {
            return this.总承包服务费项Field;
        }
        set {
            this.总承包服务费项Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 措施项目标题 {

    private List<措施项目清单> 措施项目清单Field;
    
    private string 序号Field;
    
    private string 名称Field;
    private string 项目编码Field;
    
    /// <remarks/>
    [XmlElementAttribute("措施项目清单", IsNullable = false)]
    public List<措施项目清单> 措施项目清单
    {
        get {
            return this.措施项目清单Field;
        }
        set {
            this.措施项目清单Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号 {
        get {
            return this.序号Field;
        }
        set {
            this.序号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 名称 {
        get {
            return this.名称Field;
        }
        set {
            this.名称Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 项目编码
    {
        get
        {
            return this.项目编码Field;
        }
        set
        {
            this.项目编码Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 措施项目清单 {
    
    private string 序号Field;
    
    private string 名称Field;
    
    private string 单位Field;
    
    private string 数量Field;
    
    private string 计费基础表达式Field;
    
    private string 计费基础金额Field;
    
  
    private string 费率Field;
    
    private string 综合合价Field;
    
  
    private string 人工费合计Field;
    
 

    private string 材料费合计Field;
    
   

    private string 机械费合计Field;

    private string 主材费合计Field;
   
  
    
 

    private string 设备费合计Field;
    
  

    private string 管理费合计Field;
    
   
    private string 利润合计Field;
    
   

    private string 风险合计Field;
    
    
    private string 规费合计Field;
    
    private string 税金合计Field;
    
    private bool 公式组价Field;
    
    private string 行类别Field;
    
    private string 备注Field;

    private string 清单编码Field; 
    private List<定额子目> m_定额子目;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号 {
        get {
            return this.序号Field;
        }
        set {
            this.序号Field = value;
        }
    }
      /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 清单编码
    {
        get {
            return this.清单编码Field;
        }
        set {
            this.清单编码Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 名称 {
        get {
            return this.名称Field;
        }
        set {
            this.名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 单位 {
        get {
            return this.单位Field;
        }
        set {
            this.单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 数量 {
        get {
            return this.数量Field;
        }
        set {
            this.数量Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 计费基础表达式 {
        get {
            return this.计费基础表达式Field;
        }
        set {
            this.计费基础表达式Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 计费基础金额 {
        get {
            return this.计费基础金额Field;
        }
        set {
            this.计费基础金额Field = value;
        }
    }
    
  
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 费率 {
        get {
            return this.费率Field;
        }
        set {
            this.费率Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 综合合价
    {
        get {
            return this.综合合价Field;
        }
        set {
            this.综合合价Field = value;
        }
    }
    

    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 人工费合计
    {
        get {
            return this.人工费合计Field;
        }
        set {
            this.人工费合计Field = value;
        }
    }
    
  
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 材料费合计
    {
        get {
            return this.材料费合计Field;
        }
        set {
            this.材料费合计Field = value;
        }
    }
    

    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 机械费合计
    {
        get {
            return this.机械费合计Field;
        }
        set {
            this.机械费合计Field = value;
        }
    }
    
 
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 主材费合计
    {
        get {
            return this.主材费合计Field;
        }
        set {
            this.主材费合计Field = value;
        }
    }
    

    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 设备费合计
    {
        get {
            return this.设备费合计Field;
        }
        set {
            this.设备费合计Field = value;
        }
    }
    

    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 管理费合计
    {
        get {
            return this.管理费合计Field;
        }
        set {
            this.管理费合计Field = value;
        }
    }
    

    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 利润合计
    {
        get {
            return this.利润合计Field;
        }
        set {
            this.利润合计Field = value;
        }
    }
    
 
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 风险合计
    {
        get {
            return this.风险合计Field;
        }
        set {
            this.风险合计Field = value;
        }
    }
    

    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 规费合计 {
        get {
            return this.规费合计Field;
        }
        set {
            this.规费合计Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 税金合计 {
        get {
            return this.税金合计Field;
        }
        set {
            this.税金合计Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool 公式组价 {
        get {
            return this.公式组价Field;
        }
        set {
            this.公式组价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 行类别 {
        get {
            return this.行类别Field;
        }
        set {
            this.行类别Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 备注 {
        get {
            return this.备注Field;
        }
        set {
            this.备注Field = value;
        }
    }

    [XmlElementAttribute("定额子目", IsNullable = false)]
    public List<定额子目> 定额子目
    {
        get { return m_定额子目; }
        set { m_定额子目 = value; }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 暂列金额明细 {
    
    private string 序号Field;
    
    private string 项目名称Field;
    
    private string 计量单位Field;
    
    private string 暂定金额Field;
    
    private string 备注Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号 {
        get {
            return this.序号Field;
        }
        set {
            this.序号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 项目名称 {
        get {
            return this.项目名称Field;
        }
        set {
            this.项目名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 计量单位 {
        get {
            return this.计量单位Field;
        }
        set {
            this.计量单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 暂定金额 {
        get {
            return this.暂定金额Field;
        }
        set {
            this.暂定金额Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 备注 {
        get {
            return this.备注Field;
        }
        set {
            this.备注Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 暂列金额明细表 {
    
    private 暂列金额明细[] 暂列金额明细Field;

    [XmlElementAttribute("暂列金额明细", IsNullable = false)]
    public 暂列金额明细[] 暂列金额明细 {
        get {
            return this.暂列金额明细Field;
        }
        set {
            this.暂列金额明细Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 规费税金清单表 {

    private List<规费税金项> 规费税金项Field;
    
    /// <remarks/>
    [XmlElementAttribute("规费税金项", IsNullable = false)]
    public List<规费税金项> 规费税金项
    {
        get {
            return this.规费税金项Field;
        }
        set {
            this.规费税金项Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 规费税金项 {
    
    private string 序号Field;
    
    private string 费用名称Field;
    
    private string 行费用代号Field;
    
    private string 取费基数Field;

    private string 费率Field;

    private string 金额Field;
    
    private string 费用类别Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号 {
        get {
            return this.序号Field;
        }
        set {
            this.序号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 费用名称 {
        get {
            return this.费用名称Field;
        }
        set {
            this.费用名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 行费用代号 {
        get {
            return this.行费用代号Field;
        }
        set {
            this.行费用代号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 取费基数 {
        get {
            return this.取费基数Field;
        }
        set {
            this.取费基数Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string  费率 {
        get {
            return this.费率Field;
        }
        set {
            this.费率Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 金额 {
        get {
            return this.金额Field;
        }
        set {
            this.金额Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 费用类别 {
        get {
            return this.费用类别Field;
        }
        set {
            this.费用类别Field = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 计日工表 {

    private List<计日工项> 计日工项Field;
    
    /// <remarks/>
    [XmlElementAttribute("计日工项", IsNullable = false)]
    public List<计日工项> 计日工项
    {
        get {
            return this.计日工项Field;
        }
        set {
            this.计日工项Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 计日工项 {
    
    private string 编号Field;
    
    private string 名称Field;
    
    private string 单位Field;
    
    private string 综合单价Field;
    
    private string 合价Field;
    
    private string 暂定数量Field;
    
    private string 类别Field;
    
    private string 备注Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编号 {
        get {
            return this.编号Field;
        }
        set {
            this.编号Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 名称 {
        get {
            return this.名称Field;
        }
        set {
            this.名称Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 单位 {
        get {
            return this.单位Field;
        }
        set {
            this.单位Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 综合单价 {
        get {
            return this.综合单价Field;
        }
        set {
            this.综合单价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 合价 {
        get {
            return this.合价Field;
        }
        set {
            this.合价Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 暂定数量 {
        get {
            return this.暂定数量Field;
        }
        set {
            this.暂定数量Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 类别 {
        get {
            return this.类别Field;
        }
        set {
            this.类别Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 备注 {
        get {
            return this.备注Field;
        }
        set {
            this.备注Field = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 措施项目表 {
    
    private 措施项目标题[] 措施项目标题Field;
    
    /// <remarks/>

    [XmlElementAttribute("措施项目标题", IsNullable = false)] 
    public 措施项目标题[] 措施项目标题 {
        get {
            return this.措施项目标题Field;
        }
        set {
            this.措施项目标题Field = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class 需评审的材料表
{
    private List<评审材料> M_评审材料;

    [XmlElementAttribute("评审材料", IsNullable = false)]
    public List<评审材料> 评审材料
    {
        get { return M_评审材料; }
        set { M_评审材料 = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class 材料设备暂估价
{
    private List<材料设备暂估价明细> M_材料设备暂估价明细;

    [XmlElementAttribute("材料设备暂估价明细", IsNullable = false)]
    public List<材料设备暂估价明细> 材料设备暂估价明细
    {
        get { return M_材料设备暂估价明细; }
        set { M_材料设备暂估价明细 = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class 甲供材料或设备表
{
    private List<甲供材料或设备> M_甲供材料或设备;

    [XmlElementAttribute("甲供材料或设备", IsNullable = false)]
    public List<甲供材料或设备> 甲供材料或设备
    {
        get { return M_甲供材料或设备; }
        set { M_甲供材料或设备 = value; }
    }
}
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class 人材机库
{
    private List<人材机> M_人才机;

    [XmlElementAttribute("人材机", IsNullable = false)]
    public List<人材机> 人才机
    {
        get { return M_人才机; }
        set { M_人才机 = value; }
    }
}
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class 投标信息表
{
    private string 投标人Field;
    private string 投标工期Field;
    private string 总报价Field;
    private string 总措施项目费Field;
    private string 安全文明施工措施费Field;

    private string 质量承诺Field;

    private string 投标保证金Field;

    private string 担保类型Field;

    private string 项目经理或注册建造师Field;

    private string 项目经理或建造师注册号Field;

    private string 编制人员1Field;

    private string 注册号1Field;

    private string 编制人员2Field;

    private string 注册号2Field;

    private string 编制人员3Field;

    private string 注册号3Field;

    private string 编制时间Field;

    private string 备注Field;
  
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 投标人
    {
        get
        {
            return this.投标人Field;
        }
        set
        {
            this.投标人Field = value;
        }
    }
   
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 投标工期
    {
        get
        {
            return this.投标工期Field;
        }
        set
        {
            this.投标工期Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 总报价
    {
        get
        {
            return this.总报价Field;
        }
        set
        {
            this.总报价Field = value;
        }
    } 
 
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 总措施项目费
    {
        get
        {
            return this.总措施项目费Field;
        }
        set
        {
            this.总措施项目费Field = value;
        }
    }
   

  

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 安全文明施工措施费
    {
        get
        {
            return this.安全文明施工措施费Field;
        }
        set
        {
            this.安全文明施工措施费Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 质量承诺
    {
        get
        {
            return this.质量承诺Field;
        }
        set
        {
            this.质量承诺Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 投标保证金
    {
        get
        {
            return this.投标保证金Field;
        }
        set
        {
            this.投标保证金Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 担保类型
    {
        get
        {
            return this.担保类型Field;
        }
        set
        {
            this.担保类型Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 项目经理或注册建造师
    {
        get
        {
            return this.项目经理或注册建造师Field;
        }
        set
        {
            this.项目经理或注册建造师Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 项目经理或建造师注册号
    {
        get
        {
            return this.项目经理或建造师注册号Field;
        }
        set
        {
            this.项目经理或建造师注册号Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编制人员1
    {
        get
        {
            return this.编制人员1Field;
        }
        set
        {
            this.编制人员1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 注册号1
    {
        get
        {
            return this.注册号1Field;
        }
        set
        {
            this.注册号1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编制人员2
    {
        get
        {
            return this.编制人员2Field;
        }
        set
        {
            this.编制人员2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 注册号2
    {
        get
        {
            return this.注册号2Field;
        }
        set
        {
            this.注册号2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编制人员3
    {
        get
        {
            return this.编制人员3Field;
        }
        set
        {
            this.编制人员3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 注册号3
    {
        get
        {
            return this.注册号3Field;
        }
        set
        {
            this.注册号3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 编制时间
    {
        get
        {
            return this.编制时间Field;
        }
        set
        {
            this.编制时间Field = value;
        }
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 备注
    {
        get
        {
            return this.备注Field;
        }
        set
        {
            this.备注Field = value;
        }
    }

    private string m_电脑串号;
    private string m_时间;
    private string m_锁号;
    private string m_工程代号;

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 工程代号
    {
        get { return m_工程代号; }
        set { m_工程代号 = value; }
    }



    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 电脑串号
    {
        get { return m_电脑串号; }
        set { m_电脑串号 = value; }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 时间
    {
        get { return m_时间; }
        set { m_时间 = value; }
    }
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 锁号
    {
        get { return m_锁号; }
        set { m_锁号 = value; }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class 定额子目
{

    private List<人材机含量> 人材机含量Field;

    private string 定额号Field;

    private bool 换算Field;

    private string 名称Field;

    private string 单位Field;

    private string 数量Field;

    private string 综合单价Field;

    private string 综合合价Field;

    private string 人工费单价Field;

    private string 材料费单价Field;

    private string 机械费单价Field;

    private string 主材费单价Field;

    private string 设备费单价Field;

    private string 管理费单价Field;

    private string  管理费计费基础Field;

    private string 管理费费率Field;

    private string 利润单价Field;

    private string  利润计费基础Field;

    private string 利润费率Field;

    private string 风险单价Field;

    private string  风险计费基础Field;

    private string 风险费率Field;

    private string 规费单价Field;

    private string 规费计费基础Field;

    private string 规费费率Field;

    private string 税金单价Field;

    private string 税金计费基础Field;

    private string 税金费率Field;

    private string 人工费价差Field;

    private string 材料费价差Field;

    private string 机械费价差Field;

    private string 专业类别Field;

    private sbyte 定额库代码Field;


    [XmlElementAttribute("人材机含量", IsNullable = false)] 
    public  List<人材机含量>人材机含量
    {
        get
        {
            return this.人材机含量Field;
        }
        set
        {
            this.人材机含量Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string  定额号
    {
        get
        {
            return this.定额号Field;
        }
        set
        {
            this.定额号Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool 换算
    {
        get
        {
            return this.换算Field;
        }
        set
        {
            this.换算Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string  名称
    {
        get
        {
            return this.名称Field;
        }
        set
        {
            this.名称Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 单位
    {
        get
        {
            return this.单位Field;
        }
        set
        {
            this.单位Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 数量
    {
        get
        {
            return this.数量Field;
        }
        set
        {
            this.数量Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 综合单价
    {
        get
        {
            return this.综合单价Field;
        }
        set
        {
            this.综合单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 综合合价
    {
        get
        {
            return this.综合合价Field;
        }
        set
        {
            this.综合合价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 人工费单价
    {
        get
        {
            return this.人工费单价Field;
        }
        set
        {
            this.人工费单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 材料费单价
    {
        get
        {
            return this.材料费单价Field;
        }
        set
        {
            this.材料费单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 机械费单价
    {
        get
        {
            return this.机械费单价Field;
        }
        set
        {
            this.机械费单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 主材费单价
    {
        get
        {
            return this.主材费单价Field;
        }
        set
        {
            this.主材费单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 设备费单价
    {
        get
        {
            return this.设备费单价Field;
        }
        set
        {
            this.设备费单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 管理费单价
    {
        get
        {
            return this.管理费单价Field;
        }
        set
        {
            this.管理费单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 管理费计费基础
    {
        get
        {
            return this.管理费计费基础Field;
        }
        set
        {
            this.管理费计费基础Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 管理费费率
    {
        get
        {
            return this.管理费费率Field;
        }
        set
        {
            this.管理费费率Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 利润单价
    {
        get
        {
            return this.利润单价Field;
        }
        set
        {
            this.利润单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string  利润计费基础
    {
        get
        {
            return this.利润计费基础Field;
        }
        set
        {
            this.利润计费基础Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 利润费率
    {
        get
        {
            return this.利润费率Field;
        }
        set
        {
            this.利润费率Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 风险单价
    {
        get
        {
            return this.风险单价Field;
        }
        set
        {
            this.风险单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string  风险计费基础
    {
        get
        {
            return this.风险计费基础Field;
        }
        set
        {
            this.风险计费基础Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 风险费率
    {
        get
        {
            return this.风险费率Field;
        }
        set
        {
            this.风险费率Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 规费单价
    {
        get
        {
            return this.规费单价Field;
        }
        set
        {
            this.规费单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 规费计费基础
    {
        get
        {
            return this.规费计费基础Field;
        }
        set
        {
            this.规费计费基础Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 规费费率
    {
        get
        {
            return this.规费费率Field;
        }
        set
        {
            this.规费费率Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 税金单价
    {
        get
        {
            return this.税金单价Field;
        }
        set
        {
            this.税金单价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 税金计费基础
    {
        get
        {
            return this.税金计费基础Field;
        }
        set
        {
            this.税金计费基础Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 税金费率
    {
        get
        {
            return this.税金费率Field;
        }
        set
        {
            this.税金费率Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 人工费价差
    {
        get
        {
            return this.人工费价差Field;
        }
        set
        {
            this.人工费价差Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 材料费价差
    {
        get
        {
            return this.材料费价差Field;
        }
        set
        {
            this.材料费价差Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 机械费价差
    {
        get
        {
            return this.机械费价差Field;
        }
        set
        {
            this.机械费价差Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 专业类别
    {
        get
        {
            return this.专业类别Field;
        }
        set
        {
            this.专业类别Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte 定额库代码
    {
        get
        {
            return this.定额库代码Field;
        }
        set
        {
            this.定额库代码Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class 人材机含量
{

    private string  材料号Field;

    private string 含量Field;
    private string m_原始含量;
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 材料号
    {
        get
        {
            return this.材料号Field;
        }
        set
        {
            this.材料号Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 含量
    {
        get
        {
            return this.含量Field;
        }
        set
        {
            this.含量Field = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 原始含量
    {
        get
        {
            return this.m_原始含量;
        }
        set
        {
            this.m_原始含量 = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class 人材机
{

    private List<人材机含量> 人材机含量Field;

    private string 暂估价材料关联号Field;

    private string 甲供材料关联号Field;

    private string 评审材料关联号Field;

    private string  材料号Field;

    private string  材料名Field;
    private string 类别Field;

    private string 规格型号Field;

    private string  单位Field;

    private string 单价Field;
    private string 定额价Field;

    private string 数量Field;

    private string  费用类别Field;

    private bool 主要材料标志Field;

    /// <remarks/>
    [XmlElementAttribute("人材机含量", IsNullable = false)] 
    public List< 人材机含量> 人材机含量
    {
        get
        {
            return this.人材机含量Field;
        }
        set
        {
            this.人材机含量Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 暂估价材料关联号
    {
        get
        {
            return this.暂估价材料关联号Field;
        }
        set
        {
            this.暂估价材料关联号Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 甲供材料关联号
    {
        get
        {
            return this.甲供材料关联号Field;
        }
        set
        {
            this.甲供材料关联号Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 评审材料关联号
    {
        get
        {
            return this.评审材料关联号Field;
        }
        set
        {
            this.评审材料关联号Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string  材料号
    {
        get
        {
            return this.材料号Field;
        }
        set
        {
            this.材料号Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string  材料名
    {
        get
        {
            return this.材料名Field;
        }
        set
        {
            this.材料名Field = value;
        }
    }
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 类别
    {
        get
        {
            return this.类别Field;
        }
        set
        {
            this.类别Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 规格型号
    {
        get
        {
            return this.规格型号Field;
        }
        set
        {
            this.规格型号Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string  单位
    {
        get
        {
            return this.单位Field;
        }
        set
        {
            this.单位Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 单价
    {
        get
        {
            return this.单价Field;
        }
        set
        {
            this.单价Field = value;
        }
    }
  /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 定额价
    {
        get
        {
            return this.定额价Field;
        }
        set
        {
            this.定额价Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 数量
    {
        get
        {
            return this.数量Field;
        }
        set
        {
            this.数量Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string  费用类别
    {
        get
        {
            return this.费用类别Field;
        }
        set
        {
            this.费用类别Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool 主要材料标志
    {
        get
        {
            return this.主要材料标志Field;
        }
        set
        {
            this.主要材料标志Field = value;
        }
    }
}


    
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 零星项目表 
{
    private List<零星项目标题> 零星项目标题Field;


    /// <remarks/>
    [XmlElementAttribute("零星项目标题", IsNullable = false)]
    public List<零星项目标题> 零星项目标题
    {
        get
        {
            return this.零星项目标题Field;
        }
        set
        {
            this.零星项目标题Field = value;
        }
    }

}

        
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class 零星项目标题
{
    private List<零星项目> 零星项目Field;

    private string M_序号;

    private string M_名称;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 序号
    {
        get
        {
            return this.M_序号;
        }
        set
        {
            this.M_序号 = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string 名称
    {
        get
        {
            return this.M_名称;
        }
        set
        {
            this.M_名称 = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute("零星项目", IsNullable = false)]
    public List<零星项目> 零星项目
    {
        get
        {
            return this.零星项目Field;
        }
        set
        {
            this.零星项目Field = value;
        }
    }
}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class 零星项目
    {

        private string M_序号;

        private string M_名称;
        private string M_单位;
        private string M_数量;
        private string M_单价;
        private string M_合价;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 序号
        {
            get
            {
                return this.M_序号;
            }
            set
            {
                this.M_序号 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 名称
        {
            get
            {
                return this.M_名称;
            }
            set
            {
                this.M_名称 = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 单位
        {
            get
            {
                return this.M_单位;
            }
            set
            {
                this.M_单位 = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 数量
        {
            get
            {
                return this.M_数量;
            }
            set
            {
                this.M_数量 = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 单价
        {
            get
            {
                return this.M_单价;
            }
            set
            {
                this.M_单价 = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 合价
        {
            get
            {
                return this.M_合价;
            }
            set
            {
                this.M_合价 = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class 评审材料
    {


        private string 序号Field;
        private string 材料编号Field;
        private string 名称Field;
        private string 单位Field;
        private string 规格型号Field;
        private string 数量Field;
        private string 单价Field;
        private string 合价Field;
        private string 备注Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 序号
        {
            get { return 序号Field; }
            set { 序号Field = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 材料编号
        {
            get
            {
                return this.材料编号Field;
            }
            set
            {
                this.材料编号Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 名称
        {
            get
            {
                return this.名称Field;
            }
            set
            {
                this.名称Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 单位
        {
            get
            {
                return this.单位Field;
            }
            set
            {
                this.单位Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 规格型号
        {
            get
            {
                return this.规格型号Field;
            }
            set
            {
                this.规格型号Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 数量
        {
            get
            {
                return this.数量Field;
            }
            set
            {
                this.数量Field = value;
            }
        }
         /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 单价
        {
            get
            {
                return this.单价Field;
            }
            set
            {
                this.单价Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 合价
        {
            get
            {
                return this.合价Field;
            }
            set
            {
                this.合价Field = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 备注
        {
            get
            {
                return this.备注Field;
            }
            set
            {
                this.备注Field = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class 材料设备暂估价明细
    {


        private string 序号Field;
        private string 材料或设备编号Field;
        private string 材料名称Field;
        private string 规格型号Field;

        private string 计量单位Field;
        private string 数量Field;
        private string 暂估单价Field;
        private string 合价Field;
        private string 备注Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 序号
        {
            get { return 序号Field; }
            set { 序号Field = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 材料或设备编号
        {
            get
            {
                return this.材料或设备编号Field;
            }
            set
            {
                this.材料或设备编号Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 材料名称
        {
            get
            {
                return this.材料名称Field;
            }
            set
            {
                this.材料名称Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 规格型号
        {
            get
            {
                return this.规格型号Field;
            }
            set
            {
                this.规格型号Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 计量单位
        {
            get
            {
                return this.计量单位Field;
            }
            set
            {
                this.计量单位Field = value;
            }
        }
       
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 数量
        {
            get
            {
                return this.数量Field;
            }
            set
            {
                this.数量Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 暂估单价
        {
            get
            {
                return this.暂估单价Field;
            }
            set
            {
                this.暂估单价Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 合价
        {
            get
            {
                return this.合价Field;
            }
            set
            {
                this.合价Field = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 备注
        {
            get
            {
                return this.备注Field;
            }
            set
            {
                this.备注Field = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class 甲供材料或设备
    {


        private string 序号Field;
        private string 材料或设备编号Field;
        private string 名称Field;
        private string 单位Field;
        private string 规格型号Field;
        private string 数量Field;
        private string 单价Field;
        private string 合价Field;
        private string 备注Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 序号
        {
            get { return 序号Field; }
            set { 序号Field = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 材料或设备编号
        {
            get
            {
                return this.材料或设备编号Field;
            }
            set
            {
                this.材料或设备编号Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 名称
        {
            get
            {
                return this.名称Field;
            }
            set
            {
                this.名称Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 单位
        {
            get
            {
                return this.单位Field;
            }
            set
            {
                this.单位Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 规格型号
        {
            get
            {
                return this.规格型号Field;
            }
            set
            {
                this.规格型号Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 数量
        {
            get
            {
                return this.数量Field;
            }
            set
            {
                this.数量Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 单价
        {
            get
            {
                return this.单价Field;
            }
            set
            {
                this.单价Field = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 合价
        {
            get
            {
                return this.合价Field;
            }
            set
            {
                this.合价Field = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 备注
        {
            get
            {
                return this.备注Field;
            }
            set
            {
                this.备注Field = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class 工程特征
    {


        private string 特征名称Field;
        private string 特征值Field;
     
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 特征名称
        {
            get { return 特征名称Field; }
            set { 特征名称Field = value; }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string 特征值
        {
            get
            {
                return this.特征值Field;
            }
            set
            {
                this.特征值Field = value;
            }
        }

    }
}